### ISSUE TITLE
Amplify.Auth.getCurrentUser() return different platform results when using email based auth

### ISSUE THREAD

**Issue by kjones** [aws-amplify/amplify-flutter#201]
When adding Cognito auth to a project, if email based sign-in is chosen (might apply to phone number also) then `Amplify.Auth.getCurrentUser()` return different `AuthUser` results between Android and iOS. Android returns with `AuthUser.username` set to the email address but iOS appears to return the Cognito userSub value.

**To Reproduce**
1. Configure Amplify Auth (`amplify add auth`) to use email based authentication.
    <img width="329" alt="Screen Shot 2020-08-23 at 6 56 29 PM" src="https://user-images.githubusercontent.com/1952793/91018270-9b3fb280-e5ac-11ea-9ca3-1e701661d9d9.png">
1. Sign-up, confirm, and Sign-in.
1. At some point later in time, call `Amplify.Auth.getCurrentUser()`.

**Expected behavior**
`Amplify.Auth.getCurrentUser()` should return the same results on both Android and iOS.

**Platform**
Amplify Flutter 0.0.1-dev.3
[x] Android
[x] iOS

**Comment by kjones** [comment]
Current workaround to get email on both platforms.
```dart

final authState = await Amplify.Auth.fetchAuthSession(
        options: CognitoSessionOptions(getAWSCredentials: true))
    as CognitoAuthSession;
if (authState.isSignedIn) {
  final claims = _parseJwt(authState.userPoolTokens.idToken);
  final email = claims['email'] as String;
}
```
`_parseJwt()` borrowed from here: https://stackoverflow.com/a/52021206/2929266

**Comment by srimajji** [comment]
@kjones I noticed this as well and thank you for the workaround!

**Comment by fpabl0** [comment]
@kjones yes, you are right. However, it seems to be problem of the native libraries, they have different implementation on that part. Just to note, iOS implementation is correct as the username has to be different from the email, the mistake is on the Android native library.

**Comment by haverchuck** [comment]
@kjones We have an API that should allow you to fetch the user attributes, so parsing the JWT shouldn't be necessary:
```dart
await Amplify.Auth.fetchUserAttributes()
```

**Comment by nguyenVanQuocKhanh** [comment]
The following code correctly obtains user's email in both iOS and Android:
  Future<String> _usersEmail() async {
    try {
      var attributes = (await Amplify.Auth.fetchUserAttributes()).toList();
      for (var attribute in attributes) {
        if (attribute.userAttributeKey == 'email') {
          print("user's email is ${attribute.value}");
          return '${attribute.value}';
        }
      }
      return 'no email';
    } on AuthException catch (e) {
      return '${e.message}';
    }
  }

**Comment by Jordan-Nelson** [comment]
It looks like this is a result of an issue in the amplify-ios library used by amplify-flutter when targeting iOS. There is an issue open in the amplify-ios repo currently here: https://github.com/aws-amplify/amplify-ios/issues/1255. I will follow up with the team and see if this is being looked into.

As several others have already noted, you can get the email address consistently on both platforms using `Amplify.Auth.fetchUserAttributes()` as a work around.

**Comment by julien-tamade** [comment]
Anybody know how to do the opposite, get the username on both instead of email?

**Comment by guplem** [comment]
Does this happen as well with userId? I do not have the means to test it.

I am using it to store user-related data, and now I am worried... Should I use another method to say, for example, that a note has been created by a user?

I am using this value: 
`Amplify.Auth.getCurrentUser().then((value) => print("USER: " + value.userId));`

**Comment by dnys1** [comment]
@guplem - The user ID will always be the Cognito identifier. It seems there is a discrepancy around username in some cases, but the user ID will not be affected in the same way.

**Comment by ebo8** [comment]
> Anybody know how to do the opposite, get the username on both instead of email?

I'd like to know this as well.

Currently on iOS you can get the user's username with:

`AuthUser user = await Amplify.Auth.getCurrentUser();`
`return user.username;`

But on Android it returns the email address if the user signed in with email.

**Comment by Jordan-Nelson** [comment]
Hello everyone - We have recently released a new developer preview version of the Auth category ([amplify_flutter v1.0.0-next.0](https://pub.dev/packages/amplify_flutter/versions/1.0.0-next.0)). This new version is a full re-write of the auth category in dart, and it supports Mobile, Desktop, and Web. This issue is addressed in this new version. You can read more about the developer preview release in the [blog post](https://aws.amazon.com/blogs/mobile/amplify-flutter-auth-web-and-desktop/) and [docs](https://docs.amplify.aws/lib/auth/getting-started/q/platform/flutter/). I will update this issue again once this new version is out of developer preview.

Let me know if you have any questions!

**Comment by Jordan-Nelson** [comment]
This issue has been addressed in v1.0.0 of Amplify Flutter, which is now stable. This release also includes web and desktop support for Auth, API, Analytics, and Storage. You can see the list of new features and bug fixes in the [release notes](https://github.com/aws-amplify/amplify-flutter/releases/tag/v1.0.0), and see more details on how to migrate in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/flutter/).

**Comment by jniemer** [comment]
Hello. I am using Amplify 1.2.0 and this is still an issue. AuthUser returned Amplify.Auth.getCurrentUser() has the user id as userId and username. I am using email based authentication on Android.

**Comment by dnys1** [comment]
Hi @alterhuman, please see my comment [here](https://github.com/aws-amplify/amplify-flutter/issues/3311#issuecomment-1610248451) and let me know if that resolves your issue.

When an issue is closed, it's hard for us to gain visibility into comments which are added. Please always feel free to open a new issue so that we can better assist you.
