### ISSUE TITLE
Facing 'SWIFT TASK CONTINUATION MISUSE' on real iOS device

### ISSUE THREAD

**Issue by Groseuros** [aws-amplify/amplify-flutter#2015]
### Description

**1.0.0 Developer Preview - iOS platform**

While trying to sign in with `Amplify.Auth.signInWithWebUI` on a real iOS device, I face the following issue: 
`SWIFT TASK CONTINUATION MISUSE: launchUrl(_:callbackURLScheme:preferPrivateSession:) leaked its continuation!`

Then, it's impossible to complete sign in process or get any exception.

This issue only appears on a real iOS device, same code works fine on simulator.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Setup a basic Flutter app with amplify_flutter and amplify_auth_cognito 1.0.0 Developer Preview
2. Enable social sign in with web UI
3. Build the app for iOS
4. Run the app on a real iOS device and try to sign in with any social provider
5. Face the issue

### Screenshots

![auth_error](https://user-images.githubusercontent.com/83779618/183417616-0162265a-af35-4fc2-990b-aed3459f6bf1.png)

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

### Dependencies

```bash
Dart SDK 2.17.6
Flutter SDK 3.0.5
amplify_preview_test 1.0.0+1

dependencies:
- amplify_auth_cognito 1.0.0-next.0 [amplify_auth_cognito_android amplify_auth_cognito_dart amplify_auth_cognito_ios amplify_core amplify_flutter amplify_secure_storage async flutter flutter_web_plugins meta path plugin_platform_interface]
- amplify_flutter 1.0.0-next.0 [amplify_core amplify_datastore_plugin_interface amplify_flutter_android amplify_flutter_ios amplify_secure_storage aws_common collection flutter meta plugin_platform_interface]
- cupertino_icons 1.0.5
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

transitive dependencies:
- amplify_auth_cognito_android 1.0.0-next.0 [flutter]
- amplify_auth_cognito_dart 0.1.1 [amplify_core amplify_secure_storage_dart async aws_common aws_signature_v4 built_collection built_value collection convert crypto fixnum http intl js json_annotation meta oauth2 path smithy smithy_aws stream_transform uuid worker_bee]
- amplify_auth_cognito_ios 1.0.0-next.0 [amplify_core flutter]
- amplify_core 1.0.0-next.0 [async aws_common aws_signature_v4 collection http intl json_annotation logging meta uuid]
- amplify_datastore_plugin_interface 1.0.0-next.0 [amplify_core collection flutter meta]
- amplify_flutter_android 1.0.0-next.0 [flutter]
- amplify_flutter_ios 1.0.0-next.0 [amplify_core flutter]
- amplify_secure_storage 0.1.0 [amplify_secure_storage_dart flutter]
- amplify_secure_storage_dart 0.1.0 [aws_common built_collection built_value ffi js meta win32 worker_bee]
- async 2.8.2 [collection meta]
- aws_common 0.2.1 [async collection http logging meta stream_transform uuid]
- aws_signature_v4 0.2.1 [async aws_common collection convert crypto http json_annotation meta path]
- built_collection 5.1.1
- built_value 8.4.0 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- convert 3.0.2 [typed_data]
- crclib 3.0.0 [meta tuple]
- crypto 3.0.2 [typed_data]
- ffi 2.0.1
- fixnum 1.0.1
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- oauth2 2.0.0 [collection crypto http http_parser]
- path 1.8.1
- petitparser 5.0.0 [meta]
- plugin_platform_interface 2.1.2 [meta]
- quiver 3.1.0 [matcher]
- retry 3.1.0
- shelf 1.3.2 [async collection http_parser path stack_trace stream_channel]
- sky_engine 0.0.99
- smithy 0.1.0 [aws_common built_collection built_value collection convert crypto fixnum http http_parser intl json_annotation meta path retry shelf typed_data xml]
- smithy_aws 0.1.1 [aws_common aws_signature_v4 built_collection built_value collection crclib http intl json_annotation meta path smithy xml]
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- tuple 2.0.0 [quiver]
- typed_data 1.3.1 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- win32 2.7.0 [ffi]
- worker_bee 0.1.0 [async aws_common built_collection built_value collection js meta path stack_trace stream_channel stream_transform]
- xml 6.1.0 [collection meta petitparser]
```

### Device

iPhone XR

### OS

iOS 15.6

### CLI Version

-

**Comment by dnys1** [comment]
Hi @Groseuros - we believe we've fixed this issue in the latest release. Would you be able to run `flutter pub upgrade` and verify? Cheers!

**Comment by Groseuros** [comment]
Hello @dnys1 

Unfortunately, even if I can’t see the ‘SWIFT TASK CONTINUATION MISUSE’ error anymore, I still can't get any return (stuck on a white page after auth) for:
```
final result = await Amplify.Auth.signInWithWebUI(
        provider: authProvider,
        options: const CognitoSignInWithWebUIOptions(isPreferPrivateSession: true),
      ); 
```
nor an exception when using Cancel button.

This only occurs with a physical iOS device (tested with iPhone XR, iOS 15.6), same code is working fine on iOS simulator.

**Comment by dnys1** [comment]
Okay, thanks for giving it a try! I'll keep digging into what could be causing the issue.

**Comment by dnys1** [comment]
Would you be able to share your `amplifyconfiguration.dart` file, scrubbed of any identifying info?

**Comment by Groseuros** [comment]
Here it is:

```
String amplifyconfig = '''
{
	"UserAgent":"aws-amplify-cli/2.0",
	"Version":"1.0",
	"auth":{
		"plugins":{
			"awsCognitoAuthPlugin":{
				"IdentityManager":{
					"Default":{
						
					}
				},
                                "CredentialsProvider": {
                                  "CognitoIdentity": {
                                    "Default": {
                                      "PoolId": "[POOL ID]",
                                      "Region": "[REGION]"
                                    }
                                  }
                                },
				"CognitoUserPool":{
					"Default":{
						"PoolId":"[POOL ID]",
						"AppClientId":"[APP CLIENT ID]",
						"Region":"[REGION]"
					}
				},
				"Auth":{
					"Default":{
						"OAuth":{
							"WebDomain":"[WEB DOMAIN]",
							"AppClientId":"[APP CLIENT ID]",
							"SignInRedirectURI":"[SIGNIN REDIRECT URI]",
							"SignOutRedirectURI":"[SIGNOUT REDIRECT URI]",
							"Scopes":[
								"phone",
								"email",
								"openid",
								"profile",
								"aws.cognito.signin.user.admin"
							]
						}
					}
				}
			}
		}
	}
}''';
```

**Comment by dnys1** [comment]
Thanks for that! What do you have listed for `SignInRedirectURI` and `SignOutRedirectURI`?

**Comment by Groseuros** [comment]
Something like: `{myappname}://login/` and `{myappname}://logout/` matching what I've defined on AWS

**Comment by dnys1** [comment]
Gotcha. Is `{myappname}` a single word or does it look like a bundle ID?

**Comment by Groseuros** [comment]
A single word eg: `myapp`

**Comment by dnys1** [comment]
Perfect, thanks! And which social provider are you using?

**Comment by Groseuros** [comment]
Tested with Google, Facebook and Apple

**Comment by dnys1** [comment]
Sounds good, thank you very much

**Comment by Groseuros** [comment]
Thank you for your help, let me know if you need anything else !

I only face the issue on physical iPhone with  `amplify_auth_cognito: ^1.0.0-next.0+4`, same code with `0.6.5` works fine.
Also, everything works fine on Android (simulator and physical device) as well as iOS simulator (iPhone 13 Pro - iOS 15.5). I can't explain why.

**Comment by Groseuros** [comment]
I think I've found the issue.
I noticed my deployment target was still set to 12.0, I updated to 13.0 and it seems to work now.
Really sorry about that :(

**Comment by Groseuros** [comment]
I checked the doc, it's here, it's totally my fault. 
Podfile was correctly set to 13.0 but I missed the  Runner deployment target.
Please accept my apologies

**Comment by dnys1** [comment]
All good - please continue to open tickets if you face any issue at all! We're here to help.

**Comment by roman-bigosoft** [comment]
very helpful, thanks
