### ISSUE TITLE
signInWithWebUI get error with "Unhandled Exception: Bad state: Cannot add event after closing"

### ISSUE THREAD

**Issue by Ekoios-Teddy** [aws-amplify/amplify-flutter#2733]
### Description

When I sign in with `Amplify.Auth.signInWithWebUI(
          provider: AuthProvider.google,
          options: const CognitoSignInWithWebUIOptions(
              isPreferPrivateSession: true))` on IOS, app still show browse to login google but show this error and screen loading authen in browse. I also tried to change the versions like `1.0.0-next.0+5`, `1.0.0-next.1`, `1.0.0-next.4` but the error doesn't go away. I also tried upgrading to the latest version but I see an issue related to the latest version - https://github.com/aws-amplify/amplify-flutter/issues/2726. This only occur with ios, it work on android.
<img width="700" alt="Screenshot 2023-03-08 at 00 56 15" src="https://user-images.githubusercontent.com/83799773/223508211-b4d97a73-e51d-4238-8377-82bc7f6a986c.png">
![Simulator Screen Shot - iPhone 14 Plus - 2023-03-08 at 00 57 56](https://user-images.githubusercontent.com/83799773/223508651-b4aec050-4fe8-4042-83a5-7cf287aeb0a4.png)
<img width="696" alt="Screenshot 2023-03-08 at 01 00 23" src="https://user-images.githubusercontent.com/83799773/223509176-8599fd48-63ca-4493-bc12-6d4c44e891fe.png">

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.6

### Amplify Flutter Version

1.0.0-next.1

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @Ekoios-Teddy - sorry you are facing this issue. Can you please try again with the latest version? We have just released a fix for HostedUI which should solve these issues.

**Comment by Ekoios-Teddy** [comment]
@dnys1 I have just update latest version but still get same error. Screen keep loading with not finish auth flow. `SWIFT TASK CONTINUATION MISUSE: launchUrl(_:callbackURLScheme:preferPrivateSession:) leaked its continuation!`. I'm trying with Ios simulator. Thanks for helping.
![Screenshot 2023-03-09 at 10 11 18](https://user-images.githubusercontent.com/83799773/223906728-554120e1-209e-4d5d-b2f4-7144fd021683.png)
![simulator_screenshot_F261AC8A-1F1D-4448-AB5E-AE5CCDB8CC04](https://user-images.githubusercontent.com/83799773/223906835-64c09aea-706c-48f4-9c6d-9ebd7f427a51.png)

**Comment by Ekoios-Teddy** [comment]
@dnys1 I'm building app with android real device (latest version amplify) and i get error with ` Amplify.configure(amplifyconfig)`. I have called this successfully with same `amplifyconfiguration.dart` json in that file. What happening? btw, can you let me know with old version working stably. thank you so much!
![Screenshot 2023-03-09 at 10 37 54](https://user-images.githubusercontent.com/83799773/223910490-05f6a295-ee2b-44c3-b43e-b3f19854822a.png)

**Comment by Ekoios-Teddy** [comment]
@dnys1 please help me!. Is there any way for me to login with google on Ios and web? Currently only working on android.

**Comment by dnys1** [comment]
Hi @Ekoios-Teddy, sorry for the late reply. Please make sure your Xcode project has its minimum deployment version set to 13.0.

<img width="2032" alt="Screenshot 2023-03-13 at 8 41 14 AM" src="https://user-images.githubusercontent.com/24740863/224753431-053a3b89-1d97-4304-841f-c3013349f8ee.png">

<img width="2032" alt="Screenshot 2023-03-13 at 8 43 54 AM" src="https://user-images.githubusercontent.com/24740863/224753493-4ef7423a-049a-4aa2-a72d-7e98aee5b7ac.png">

**Comment by Ekoios-Teddy** [comment]
@dnys1 thanks so much, it work. By the way, please let me know how can i check expire token (Idtoken) to handle something.  Now i'm using `Amplify.Auth.fetchAuthSession()` to check `isSignedIn` status but it alway value `true` though token expired. I want to check token expired to`SignOut ` and Login again. Thanks you!

**Comment by dnys1** [comment]
I'm glad to hear that, @Ekoios-Teddy. Here's how you can retrieve the ID token expiration:

```dart
final plugin = Amplify.Auth.getPlugin(AmplifyAuthCognito.pluginKey);
final session = await plugin.fetchAuthSession();
final idTokenExp =
    session.userPoolTokensResult.valueOrNull?.idToken.claims.expiration;
```

**Comment by Ekoios-Teddy** [comment]
@dnys1 thanks so much.  Before, i'm using this to get token expired time  ` try {
      final CognitoAuthSession result = await Amplify.Auth.fetchAuthSession(
              options: const CognitoSessionOptions(forceRefresh: true))
          as CognitoAuthSession;
      final idTokenExp = result.credentialsResult.value.expiration;
      print('123123 ${result.credentialsResult.value.expiration}');
    } on AuthException catch (e) {}` and time expired greater than 1 hour from login. So with your above code, it correct like setting client. So I have 2 question to need explain from you, please help me clear that. The first is why have there 2 different results in expired token time. The secondary is when user using app and token get expiration so how event emit for me to listen this. I'm following your document and seem it not work. This is from your guide of document `StreamSubscription<HubEvent> hubSubscription = Amplify.Hub.listen([HubChannel.Auth], (hubEvent) {
  switch(hubEvent.eventName) {
    case 'SIGNED_IN':
      print('USER IS SIGNED IN');
      break;
    case 'SIGNED_OUT':
      print('USER IS SIGNED OUT');
      break;
    case 'SESSION_EXPIRED':
      print('SESSION HAS EXPIRED');
      break;
    case 'USER_DELETED':
      print('USER HAS BEEN DELETED');
      break;
  }
`.I look forward to hearing from you soon, thank you very much

**Comment by dnys1** [comment]
Hi @Ekoios-Teddy, it seems like some of the confusion may be around using the `forceRefresh: true` parameter. When this is set, the ID token will be refreshed and the expiration will be updated. Calling without `forceRefresh: true` will return the current token if it's not expired, or a new token if it was expired before.

In order to get a stream of token changes, we don't have a good way to do this currently. I believe there may be valid reasons to expose this, and can create a feature request if this is something you'd like to see.

**Comment by Ekoios-Teddy** [comment]
@dnys1 know i'm using ` Future<bool> fetchAuthSession() async {
    try {
      final CognitoAuthSession result = await Amplify.Auth.fetchAuthSession(
              options: const CognitoSessionOptions(forceRefresh: true))
          as CognitoAuthSession;
      if (!result.isSignedIn) {
        return false;
      }
      await sharedPref.saveToken(result.userPoolTokensResult.value.idToken.raw);
      return true;
    } on AuthException catch (e) {
      return false;
    }
  }` after open app and save token to local device. Please comment to help me, is this ok?. And like you say, now stream token change is not available so is there a way to resolve the issue of expired tokens while using the app? Thank you so much for your quick and enthusiastic reply 🤩🤩

**Comment by dnys1** [comment]
I would recommend not saving tokens in shared preferences and just calling `fetchAuthSession` when you need the token. This way, you will be guaranteed to always have a fresh token. You also don't need to have `forceRefresh: true` since the token will be automatically refreshed when needed.

**Comment by Ekoios-Teddy** [comment]
@dnys1 thanks you so much, very thanks. I will implement your solution and quick feedback, thanks for helping.

**Comment by dnys1** [comment]
My pleasure! I will close this issue for now, but please let me know if you continue to face issues.
