### ISSUE TITLE
 Unhandled Exception: Amplify plugin was not added

### ISSUE THREAD

**Issue by FlutterEngineer** [aws-amplify/amplify-flutter#302]
I am using this code   

```dart
void _configureAmplify() async {
 

    // Add Pinpoint and Cognito Plugins
    AmplifyAnalyticsPinpoint analyticsPlugin = AmplifyAnalyticsPinpoint();
    AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
    amplifyInstance.addPlugin(authPlugins: [authPlugin]);
    amplifyInstance.addPlugin(analyticsPlugins: [analyticsPlugin]);

    // Once Plugins are added, configure Amplify
    await amplifyInstance.configure(amplifyconfig);
    try {

        _amplifyConfigured = true;

    } catch (e) {
      print(e);
    }

  }
```
when in run _configureAmplify() it showing <br>I/flutter (24087): ```
Auth plugin was not added
<br>E/flutter (24087): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Amplify plugin was not added

```

**Comment by Amplifiyer** [comment]
@FlutterEngineer, is there any chance your Amplify initialization gets called multiple times? Currently `addPlugin` is not allowed to be called multiple times for the same plugin or after a configure has been called. Can you change your code to the following for now and see if that helps

```dart
void _configureAmplify() async {
 
  if(!_amplifyConfigured) { //New
    // Add Pinpoint and Cognito Plugins
    AmplifyAnalyticsPinpoint analyticsPlugin = AmplifyAnalyticsPinpoint();
    AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
    amplifyInstance.addPlugin(authPlugins: [authPlugin]);
    amplifyInstance.addPlugin(analyticsPlugins: [analyticsPlugin]);

    try {
      // Once Plugins are added, configure Amplify
      await amplifyInstance.configure(amplifyconfig);
      _amplifyConfigured = true;

    } catch (e) {
      print(e);
    }
  } // New 
}
```

**Comment by fsilavong** [comment]
Similar error occurred for me when I used the code suggested above:

```
I/CameraManagerGlobal( 4090): Connecting to camera service
I/amplify:flutter:auth_cognito( 4090): Added Auth plugin
I/amplify:flutter:api( 4090): Added API plugin
D/AWSMobileClient( 4090): Using the SignInProviderConfig from `awsconfiguration.json`.
D/AWSMobileClient( 4090): Inspecting user state details
E/flutter ( 4090): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: AmplifyException(message: Auth plugin has not been added to Amplify, recoverySuggestion: Add Auth plugin to Amplify and call configure before calling Auth related APIs, underlyingException: null)
E/flutter ( 4090): #0      AuthCategory.fetchAuthSession
package:amplify_flutter/categories/amplify_auth_category.dart:161
E/flutter ( 4090): #1      _LoginScreenState._checkIfLogin
package:front_end_app/login.dart:90
E/flutter ( 4090): #2      _LoginScreenState.initState
package:front_end_app/login.dart:107
```

**Comment by bostaginting** [comment]
hi, I'm facing the same problem, any solution will be appreciated, thank you.

**Comment by dnys1** [comment]
Hi @bostaginting - can you describe more about your issue? Any logs and code you can share to reproduce the problem would be greatly appreciated.

**Comment by bostaginting** [comment]
hi @dnys1 so I've got this error when try to fetch session on amplify 

<img width="301" alt="Screen Shot 2021-09-24 at 23 06 47" src="https://user-images.githubusercontent.com/40355270/134706779-78c218e7-d025-4761-91cb-7f584458b854.png">

this is my app.dart file when i configure the amplify

<img width="592" alt="Screen Shot 2021-09-24 at 23 08 50" src="https://user-images.githubusercontent.com/40355270/134706886-15a3262b-e1ba-4eb3-a35c-a00ee477ceb2.png">

and this is the code where i got the error, on the catch

<img width="615" alt="Screen Shot 2021-09-24 at 23 09 00" src="https://user-images.githubusercontent.com/40355270/134707005-2d4e637e-05b6-4ebd-80b9-f9da30123052.png">

any suggestion will be appreciated thank you.

**Comment by dnys1** [comment]
Thank you for that information, @bostaginting. Can you also provide the Amplify versions you're using in the `pubspec.yaml` file? I will start looking into what could be causing this.

**Comment by bostaginting** [comment]
<img width="274" alt="Screen Shot 2021-09-24 at 23 35 05" src="https://user-images.githubusercontent.com/40355270/134710208-8c4d63e4-2d32-414a-af0e-ae7dde700e47.png">

Hi @dnys1  thanks for the reply, this is my amplify version.

**Comment by dnys1** [comment]
Would you be able to update to the latest version by either running `flutter pub upgrade` or bumping the version numbers to `^0.2.4`. It's possible this was an issue in one of the native libraries which has recently been fixed.

I will continue to look into in on my end. Thanks!

**Comment by bostaginting** [comment]
ok, @dnys1 I will try to upgrade the amplify package version to ^ 0.2.4, and will inform you ASAP, thank you so much!

**Comment by bostaginting** [comment]
![IMG_1965](https://user-images.githubusercontent.com/40355270/134802850-6d45bcf6-c977-401d-9f3b-e1d21f3c955b.jpg)

Hi @dnys1 after updated the amplify package to `^0.2.4` I've git this error when try to get user status

<img width="533" alt="Screen Shot 2021-09-26 at 16 52 52" src="https://user-images.githubusercontent.com/40355270/134802897-b9fc00fd-8f9f-47e5-80ae-35c333e5e159.png">

**Comment by dnys1** [comment]
Thanks, @bostaginting, can you make sure you are calling `_configureAmplify` before `_checkSession`? The error you're seeing is from `Amplify.configure` not completing before `_checkSession`.

**Comment by bostaginting** [comment]
okay @dnys1 , but how do I know when `_configureAmplify ` is done or not?

**Comment by dnys1** [comment]
You'll want to await it before calling `_checkSession` like this:

```dart
class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late final AppViewModel _viewModel = AppViewModel();

  @override
  void initState() {
    super.initState();
    _configure();
  }

  Future<void> _configure() async {
    await _configureAmplify();
    final isSignedIn = await _checkSession();
    // do something with isSignedIn
  }

  Future<void> _configureAmplify() async {
    // ...
  }

  Future<bool> _checkSession() async {
    // ...
   }
  // ...
}
```

**Comment by bostaginting** [comment]
thanks for the explanation  @dnys1 , the issue is now solved, thank you in advance!

**Comment by flgatormike** [comment]
I'm not sure how others are able to solve this. I have tried all suggestions here and I still get the same error:

```
Amplify plugin was not added
Error: AmplifyException$(message: Amplify plugin AmplifyAuthCognito was not added successfully., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: MissingPluginException(No implementation found for method addPlugin on channel com.amazonaws.amplify/auth_cognito))
    at Object.throw_ [as throw] (http://localhost:63979/dart_sdk.js:5061:11)
    at amplify.AmplifyClass.protected.addPlugin (http://localhost:63979/packages/amplify_flutter/amplify_hub.dart.lib.js:248:25)
    at addPlugin.throw (<anonymous>)
    at http://localhost:63979/dart_sdk.js:38645:38
    at _RootZone.runBinary (http://localhost:63979/dart_sdk.js:38515:59)
    at _FutureListener.thenAwait.handleError (http://localhost:63979/dart_sdk.js:33724:33)
    at handleError (http://localhost:63979/dart_sdk.js:34281:51)
    at Function._propagateToListeners (http://localhost:63979/dart_sdk.js:34307:17)
    at _Future.new.[_completeWithValue] (http://localhost:63979/dart_sdk.js:34151:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:63979/dart_sdk.js:34172:35)
    at Object._microtaskLoop (http://localhost:63979/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:63979/dart_sdk.js:38784:13)
    at http://localhost:63979/dart_sdk.js:34519:9
Error: MissingPluginException(No implementation found for method configure on channel com.amazonaws.amplify/amplify)
    at Object.throw_ [as throw] (http://localhost:63979/dart_sdk.js:5061:11)
    at MethodChannel._invokeMethod (http://localhost:63979/packages/flutter/src/services/restoration.dart.lib.js:1526:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:63979/dart_sdk.js:38640:33
    at _RootZone.runUnary (http://localhost:63979/dart_sdk.js:38511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:63979/dart_sdk.js:33713:29)
    at handleValueCallback (http://localhost:63979/dart_sdk.js:34265:49)
    at Function._propagateToListeners (http://localhost:63979/dart_sdk.js:34303:17)
    at _Future.new.[_completeWithValue] (http://localhost:63979/dart_sdk.js:34151:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:63979/dart_sdk.js:34172:35)
    at Object._microtaskLoop (http://localhost:63979/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:63979/dart_sdk.js:38784:13)
    at http://localhost:63979/dart_sdk.js:34519:9
```

**Comment by offlineprogrammer** [comment]
@flgatormike you don't need amplify_core anymore. Can you remove it from pubspec.yaml and test again

**Comment by flgatormike** [comment]
So I was getting this error while debugging with Chrome, but when I debug with the android emulator, I do not get the error. Is this expected behavior that it will not work while debugging in Chrome?

**Comment by savadmv** [comment]
**I'm getting this error in iOS. Working fine with android. I'm not testing in web** 

```dart
void configureAmplify() async {
    // Add Pinpoint and Cognito Plugins, or any other plugins you want to use

    AmplifyAnalyticsPinpoint analyticsPlugin = AmplifyAnalyticsPinpoint();
    AmplifyAuthCognito authPlugin = AmplifyAuthCognito();
    await Amplify.addPlugins([authPlugin, analyticsPlugin]);

    // Once Plugins are added, configure Amplify
    // Note: Amplify can only be configured once.

    try {
      await Amplify.configure(amplifyconfig);
    } on AmplifyAlreadyConfiguredException {
      print(
          "Tried to reconfigure Amplify; this can occur when your app restarts on Android.");
    } on AmplifyException catch (e) {
      throw AmplifyException(e.message);
    }
  }

```
**_pubspec.yaml_**

```dart
  amplify_flutter: ^0.2.10
  amplify_auth_cognito: ^0.2.10
  amplify_analytics_pinpoint: ^0.2.10

```

```
flutter: Amplify plugin was not added
flutter: Amplify plugin was not added
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: AmplifyException(message: Amplify plugin AmplifyAuthCognito was not added successfully., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: MissingPluginException(No implementation found for method addPlugin on channel com.amazonaws.amplify/auth_cognito))
#0      AmplifyClass.addPlugin (package:amplify_flutter/amplify.dart:101:9)
<asynchronous suspension>
#1      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#2      AmplifyImpl.configureAmplify (package:save_a_life_citizen/core/init/amplify_init.dart:18:5)
<asynchronous suspension>
```

**Comment by BerndWessels** [comment]
Hi
I am also getting this error on a brand new flutter project on Android
```
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:65314/Cy_dT-eNDw4=/ws
Syncing files to device sdk gphone x86...
I/flutter (27255): Amplify plugin was not added
E/flutter (27255): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: AmplifyException(message: Amplify plugin AmplifyAuthCognito was not added successfully., recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException: Null check operator used on a null value)
E/flutter (27255): #0      AmplifyClass.addPlugin (package:amplify_flutter/amplify.dart:101:9)
E/flutter (27255): <asynchronous suspension>
E/flutter (27255): #1      AuthenticationService.init (package:my_product_app/app/services/authentication.dart:15:5)
E/flutter (27255): <asynchronous suspension>
E/flutter (27255): #2      GetInstance.putAsync (package:get/get_instance/src/get_instance.dart:62:19)
E/flutter (27255): <asynchronous suspension>
E/flutter (27255): #3      initServices (package:my_product_app/main.dart:8:3)
E/flutter (27255): <asynchronous suspension>
E/flutter (27255): #4      main (package:my_product_app/main.dart:12:3)
E/flutter (27255): <asynchronous suspension>
E/flutter (27255): 
```

pubspec.yaml
```
name: my_product_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  amplify_auth_cognito: ^0.2.10
  amplify_flutter: ^0.2.10

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
```

doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19044.1387], locale en-NZ)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.0)
[√] Connected device (3 available)

• No issues found!
```

**Comment by rstrazz** [comment]
I'm getting the same issue:

Amplify plugin was not added
Could not configure Amplify: AmplifyException(message: Amplify plugin AmplifyAuthCognito was not added successfully.,
recoverySuggestion: We currently don't have a recovery suggestion for this exception., underlyingException:
MissingPluginException(No implementation found for method addPlugin on channel com.amazonaws.amplify/auth_cognito))

**Comment by aqarcoSys** [comment]
@rstrazz I'm getting this exact error also if you delete the app from the simulator and run it again, the error disappears, the error back with **hot reload**, anytime I change the code, the error appears again ,Anyone have a solution for that ?
![code](https://user-images.githubusercontent.com/96650423/147828365-16a57f9f-6fad-41e7-b0a4-e10647e20766.png)

`flutter doctor`
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
```

**Comment by pflugs30** [comment]
@BerndWessels I'm facing the same issue.  Did you find a resolution?  Thanks.

**Comment by abakermi** [comment]
The only solution that worker is only removing the admin query from amplify configuration file and calling graphql with multiple api name base on available auth type.

**Comment by tengwei-yuan** [comment]
I am also seeing the same issue when running code on Chrome. The code works fine on Android emulator. Any suggestions? It's been a few months.
```

dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
════════════════════════════════════════════════════════════════════════════════════════════════════
Amplify plugin was not added
Error MissingPluginException(No implementation found for method configure on channel com.amazonaws.amplify/amplify)
Error: AmplifyException$(message: Amplify plugin AmplifyAPI was not added successfully., recoverySuggestion: We currently don't
have a recovery suggestion for this exception., underlyingException: MissingPluginException(No implementation found for method
addPlugin on channel com.amazonaws.amplify/api))
    at Object.throw_ [as throw] (http://localhost:60354/dart_sdk.js:5069:11)
    at amplify.AmplifyClass.protected.addPlugin (http://localhost:60354/packages/amplify_flutter/amplify_hub.dart.lib.js:251:25)
    at addPlugin.throw (<anonymous>)
    at http://localhost:60354/dart_sdk.js:40575:38
    at _RootZone.runBinary (http://localhost:60354/dart_sdk.js:40444:59)
    at _FutureListener.thenAwait.handleError (http://localhost:60354/dart_sdk.js:35373:33)
    at handleError (http://localhost:60354/dart_sdk.js:35946:51)
    at Function._propagateToListeners (http://localhost:60354/dart_sdk.js:35972:17)
    at _Future.new.[_completeWithValue] (http://localhost:60354/dart_sdk.js:35816:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60354/dart_sdk.js:35837:35)
    at Object._microtaskLoop (http://localhost:60354/dart_sdk.js:40707:13)
    at _startMicrotaskLoop (http://localhost:60354/dart_sdk.js:40713:13)
    at http://localhost:60354/dart_sdk.js:36190:9
Error: AmplifyException$(message: Auth plugin has not been added to Amplify, recoverySuggestion: Add Auth plugin to Amplify and
call configure before calling Auth related APIs, underlyingException: null)
```

**Comment by tengwei-yuan** [comment]
> 

One thing to note is the issue didn't happen with Vue + Chrome and Flutter + Android, but it happens with Flutter + Chrome

**Comment by tengwei-yuan** [comment]
I think this can be closed. Got answer from this link: https://github.com/aws-amplify/amplify-flutter/issues/234

**Comment by akshatbhuhagal** [comment]
Whenever you get a Plugin not added exception, this is usually because you are performing a hot-reload operation AFTER adding the plugin to your app. You need to STOP the app completely and then do flutter clean and RUN it again. This was the issue for me
