### ISSUE TITLE
Amplify Configuration Issue during hot restart when using Authenticator & DataStore

### ISSUE THREAD

**Issue by afnx** [aws-amplify/amplify-flutter#3368]
### Description

As it's discussed in https://github.com/aws-amplify/amplify-flutter/issues/1658, when you do a hot restart, `Amplify.isConfigured` returns false, causing `Amplify.configure()` to throw an AmplifyAlreadyConfiguredException. Some workarounds have been suggested like muting all exceptions, but no matter which solution you choose, the Authenticator will still check if Amplify is configured by itself and think that it's not. This causes Authenticator to get stuck in the loading state and continuously print the following warning message on the console:

```
flutter: WARN  | AmplifyAuthService | Amplify is taking longer than expected to configure. Have you called `Amplify.configure()`?
```

What temporary solutions can we implement to address the Authenticator part of the issue until a PR is released to fully resolve the situation? It's currently not possible to work in this way.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [x] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Run the code below.
2. Try to perform a hot restart.

```dart
import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_authenticator/amplify_authenticator.dart';
import 'package:amplify_datastore/amplify_datastore.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';
import 'package:test_app/models/ModelProvider.dart';

import 'amplifyconfiguration.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    if (!Amplify.isConfigured) {
      await Amplify.addPlugins([
        AmplifyAuthCognito(),
        AmplifyDataStore(modelProvider: ModelProvider.instance),
        AmplifyAPI(),
      ]);
      await Amplify.configure(amplifyconfig);
    }
  } on AmplifyAlreadyConfiguredException {
    debugPrint('Amplify configuration failed.');
  }

  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Authenticator(
      onException: (exception) {
        print('[ERROR]: $exception');
      },
      child: MaterialApp(
        title: 'Authenticator Demo',
        builder: Authenticator.builder(),
        initialRoute: '/routeA',
        routes: {
          '/routeA': (BuildContext context) => const RouteA(),
          '/routeB': (BuildContext context) => const RouteB(),
        },
      ),
    );
  }
}

class RouteA extends StatelessWidget {
  const RouteA({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Route A'),
      ),
      body: Center(
        child: Column(
          children: [
            ElevatedButton(
              onPressed: () =>
                  Navigator.of(context).pushReplacementNamed('/routeB'),
              child: const Text('Goto Route B'),
            ),
            const SizedBox(height: 20),
            const SignOutButton(),
          ],
        ),
      ),
    );
  }
}

class RouteB extends StatelessWidget {
  const RouteB({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Route B'),
      ),
      body: Center(
        child: Column(
          children: [
            ElevatedButton(
              onPressed: () =>
                  Navigator.of(context).pushReplacementNamed('/routeA'),
              child: const Text('Goto Route A'),
            ),
            const SizedBox(height: 20),
            const SignOutButton(),
          ],
        ),
      ),
    );
  }
}
```

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.2.1

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi @afnx I am unable to reproduce your issue using Authenticator alone.  

Instead it appears that hot restart is broken due to the inclusion of the Datastore category.  In further tests, removing Authenticator and only having Datastore breaks hot restart. 

Can you please confirm this on your side?  If so, it appears you are unfortunately encountering the same exact issue as the one you mentioned above #1658

**Comment by afnx** [comment]
Hi @fjnoyp I apologize for any confusion. I know the main issue is that DataStore breaks hot restart, as mentioned in #1658 and Authenticator doesn't have to do anything with it. However, the reason for opening a separate issue is that there is no way to avoid this problem when using DataStore with Authenticator. It is still possible to perform a hot restart when using DataStore alone by doing some workarounds, but there is no workarounds that I know for using it with Authenticator. I'd like to find a temporary solution, possibly on the Authenticator side (maybe somehow bypassing the configuration check), until the issue is completely resolved.

**Comment by fjnoyp** [comment]
Thanks for confirming @afnx .  Yes you are right, when using Datastore with Authenticator it is no longer possible to avoid.  

We are still discussing possible fixes, a temporary workaround is to update [this code](https://github.com/aws-amplify/amplify-flutter/blob/3375697f5025a8d9d8ac6e9717769cc286531cb2/packages/amplify_datastore/ios/Classes/SwiftAmplifyDataStorePlugin.swift#L154-L160) to return a success instead of a failure, and to do the same for Android. 

```
case .amplifyAlreadyConfigured:
                let flutterError = FlutterError(
                    code: "AmplifyAlreadyConfiguredException",
                    message: error.localizedDescription,
                    details: nil
```

**Comment by rorygeo** [comment]
I am also experiencing this issue.

**Comment by fjnoyp** [comment]
Hi everyone we have a fix up for this issue pending a team review and eventual release. 

However if you simply move your Amplify init logic from the main method to your initState method this issue will be fixed as well:


```
class _MyAppState extends State<MyApp> {

 @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
      try {
      if (!Amplify.isConfigured) {
        await Amplify.addPlugins([
          AmplifyAuthCognito(),
          AmplifyDataStore(modelProvider: ModelProvider.instance),
          AmplifyAPI(),
        ]);
        await Amplify.configure(amplifyconfig);
      }
    } on AmplifyAlreadyConfiguredException {
      debugPrint('Amplify configuration failed.');
    }
  }
}

```

**Comment by NikaHsn** [comment]
This has been fixed in v1.3.1. Thanks for your patience resolving this issue.

**Comment by Kevinndou15** [comment]
Was this issue resolved? I am still experiencing this problem
