### ISSUE TITLE
Unexpectedly found nil while implicitly unwrapping an Optional value: file AmplifyPlugins/AWSCognitoAuthPlugin+UserBehavior.swift

### ISSUE THREAD

**Issue by igoramidzic** [aws-amplify/amplify-flutter#501]
Calling `Amplify.Auth.getCurrentUser()` after hot restarting causes fatal error and terminates debugger.
Please let me know if this issue has been resolved already. I can't find one currently. Thanks.

**To Reproduce**
1. Configure Amplify with AmplifyAuthCognito
2. Start debugger
3. Hot restart
4. Call `Amplify.Auth.getCurrentUser()`
5. `Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file AmplifyPlugins/AWSCognitoAuthPlugin+UserBehavior.swift, line 95`

**Expected behavior**
Should not throw a fatal error.

**Screenshots**
![Screen Shot 2021-04-07 at 7 50 08 PM](https://user-images.githubusercontent.com/22078300/113948278-7a923900-97da-11eb-9162-fa3603a55ed3.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android (It works fine on android)
[X] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.0.4 at /Users/igoramidzic/flutter
    • Framework revision b1395592de (6 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/igoramidzic/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • DF71849E-E3E8-4F68-90FF-330D01EE450C • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      89.0.4389.114

• No issues found!
```

</details>

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max Simulator
 - OS: iOS 14.4

**Additional context**

**Comment by Ashish-Nanda** [comment]
@igoramidzic What version of Amplify Flutter do you have installed? 
Also I would suggest you move the `Amplify.Auth.getCurrentUser()` call outside of the configuration block.

**Comment by igoramidzic** [comment]
@Ashish-Nanda 
```
dependencies:
  flutter:
    sdk: flutter
  amplify_auth_cognito: ^0.1.1
  amplify_flutter: ^0.1.1
```

And I put the call to `getCurrentUser()` there for ease of demo. It throws the same error when called from elsewhere, and it also works perfectly in that location when you initially start the debugger. Only fails on the second call when you hot restart.

**Comment by maximilianschelbach** [comment]
This problem happens in general always after a hot restart, when the Cognito plugin is used. Besides `getCurrentUser`, also `fetchAuthSession`, fails as well.

It seems that this is because the `authorizationProvider` is `nil` after the hot restart.

`AWSCognitoAuthPlugin.swift` line 25:
```swift
var authorizationProvider: AuthorizationProviderBehavior!
```

This makes an assertion that the variable is not `nil` every time it is used. The implementations of `getCurrentUser` and `fetchAuthSession` are accessing the variables and cause this error. This is due to that the `Amplify.addPlugin(AmplifyAuthCognito())` call does trigger a recreation of the `AWSCognitoAuthPlugin` instance in swift. But the instance never gets configured because that call is canceled with a `AmplifyAlreadyConfiguredException` error.

After trying a bit around I found only one (not really nice) solution. I've edited the `AuthCategory.swift` file:
```swift
public func add(plugin: AuthCategoryPlugin) throws { // line 50
   guard plugins.isEmpty else { return } // I've added this line
   let key = plugin.key
   guard !key.isEmpty else {
       let pluginDescription = String(describing: plugin)
       let error = AuthError.configuration("Plugin \(pluginDescription) has an empty `key`.",
           "Set the `key` property for \(String(describing: plugin))")
       throw error
   }

   plugins[plugin.key] = plugin
}
```

This at least makes it able to develop on iOS without constantly rebuilding and restart the whole app. But this issue should be fixed with a real solution.

**Comment by igoramidzic** [comment]
Max! You the man.
I can confirm that this suggestion works for me.

Hopefully we can work toward a more permanent solution.

For those, like me, who struggled to find the file for the temporary solution presented by @maximilianschelbach: 
`ios/Pods/Amplify/Amplify/Categories/Auth/AuthCategory.swift`

**Comment by jcowley** [comment]
I'm experiencing this as well, though it also fails when the app loads. Any call to `Amplify.Auth.getCurrentUser()` or `Amplify.Auth.fetchAuthSession()` when there is no session will cause the app to crash with the error noted above.

**Comment by haverchuck** [comment]
@igoramidzic The issue with hot restart should be fixed in version 0.1.2!

**Comment by igoramidzic** [comment]
That didn't fix it for me.
Can someone else check? @jcowley @maximilianschelbach

**Comment by jcowley** [comment]
@igoramidzic Not seeing this anymore. Did a `flutter clean` and also cleared the pod cache.

**Comment by haverchuck** [comment]
@jcowley @igoramidzic Which version of Amplify pod are you seeing in your Podfile.lock?

**Comment by igoramidzic** [comment]
@haverchuck 

- AWSPluginsCore (1.7.0):
    - Amplify (= 1.7.0)
    - AWSCore (~> 2.23.0)

**Comment by jcowley** [comment]
@haverchuck 
```
  - AWSPluginsCore (1.8.0):
    - Amplify (= 1.8.0)
    - AWSCore (~> 2.23.3)
```

Steps are pretty straight forward:

1. Start debugging (I'm using vscode)
2. Hit reload on the debugger menu
Result: 
* First, you get an `AmplifyAlreadyConfiguredException` because the new `isConfigured` attribute (#303) doesn't persist across restarts, but the amplify configuration does. (This issue existed in 0.1.1 and 0.1.0 versions of the library)
* Second, after stepping over that exception, the app crashes with the `Unexpectedly found nil`. This is triggered by my code calling `Amplify.Auth.fetchAuthSession()` to see if the user is logged in.

**Comment by haverchuck** [comment]
@jcowley @igoramidzic I believe the fix for this on the iOS platform was included in Amplify pod 1.8.1. If possible for your project, could you try removing your `Podfile.lock`?

**Comment by jcowley** [comment]
Ok, finally got it to work. Thanks for your help and patience @haverchuck. Deleting `Podfile.lock` and re-running `pod install` wasn't doing it. I was still getting 1.8.0. Neither was `pod cache clean --all`. Finally got it to update to 1.8.1 by doing:

```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

**Comment by Ashish-Nanda** [comment]
@jcowley Thanks for confirming the fix. Closing this issue as the fix has been released and verified.
