### ISSUE TITLE
Amplify flutter sign in with federated provider (Google/Apple) not following deep link redirect on real IOS device

### ISSUE THREAD

**Issue by pcittadini** [aws-amplify/amplify-flutter#6105]
### Description

After setting up a Cognito SSO federation with Apple and Google. Using the followign approach:

```
return await Amplify.Auth.signInWithWebUI(
        provider: provider,
        options: SignInWithWebUIOptions(
          pluginOptions:
              CognitoSignInWithWebUIPluginOptions(isPreferPrivateSession: true),
        ),
      );
```

- Deep link is using custom scheme like the following : mycustomscheme://appname.link
- This is validated and working as it can be open from other apps and browsers.
- The whole flow works on emulator and on Android (and from Cognito web login page).
- All transport exceptions have been enabled on info.plist 
- Url types are configured
- Event the domains for google and apple were whitelisted in the App Transport Security Settings sections.

The webview opens showing the overlay with the apple loging prompt, or the google login page. After succesfully logging in webview a blank page is showed and the deep link returned is not followed for completing token exchange.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [x] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Create a new federation from Cognito to Google or Apple
Configure universal links and deep links
Add auth model for SSO provider
Try logging in with Google or Apple from a phyisical iOS device

### Platforms

- [x] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.29.2

### Amplify Flutter Version

2.6.1

### Deployment Method

Custom Pipeline

### Schema

```GraphQL

```

**Comment by aktumut** [comment]
same here!

**Comment by KeidiKD** [comment]
I have been having the same issue as well. The app stays in a blank screen after signing in successfully. It seems that the issue is related to how the web ui handles the redirect back to the app via the deeplink

**Comment by tyllark** [comment]
Hello @pcittadini, thanks for taking the time to open up this issue. We will investigate and get back to you when we have an update.

**Comment by tyllark** [comment]
Hello @pcittadini @ProgUser145 @aktumut @KeidiKD, I've been unable to reproduce the issue on my physical iOS device. Could you please verify that you can recreate the issue with the following code and let me know if you are using a different package for routing/deep links.
```
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import 'amplify_outputs.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await _configureAmplify();

  runApp(
    MaterialApp.router(
      title: 'Auth Test',
      theme: ThemeData.dark(),
      routerConfig: _router,
    ),
  );
}

Future<void> _configureAmplify() async {
  try {
    await Amplify.addPlugins([AmplifyAuthCognito()]);
    await Amplify.configure(amplifyConfig);
    safePrint('Success configuring Amplify!');
  } on Exception catch (e) {
    safePrint('Error configuring Amplify: $e');
  }
}

final _router = GoRouter(
  routes: [
    GoRoute(
      path: '/',
      builder:
          (_, __) => Scaffold(
            appBar: AppBar(title: const Text('Home Screen')),
            body: Column(
              children: [
                ElevatedButton(
                  onPressed: _signInWithApple,
                  child: Text('Sign In With Apple'),
                ),
                ElevatedButton(onPressed: _signout, child: Text('Sign Out')),
              ],
            ),
          ),
      routes: [
        GoRoute(
          path: 'deep_link',
          builder:
              (_, __) => Scaffold(
                appBar: AppBar(title: const Text('Deep Link Screen')),
              ),
        ),
      ],
    ),
  ],
);

Future<void> _signInWithApple() async {
  try {
    await Amplify.Auth.signInWithWebUI(
      provider: AuthProvider.apple,
      options: const SignInWithWebUIOptions(
        pluginOptions: CognitoSignInWithWebUIPluginOptions(
          isPreferPrivateSession: true,
        ),
      ),
    );
  } catch (e) {
    safePrint('Sign in failed: $e');
  }
}

Future<void> _signout() async {
  try {
    await Amplify.Auth.signOut();
  } catch (e) {
    safePrint('Sign out failed: $e');
  }
}
```
https://github.com/user-attachments/assets/be0980b3-9bca-4c9e-bf68-535ad87e2494

**Comment by pcittadini** [comment]
Hi @tyllark we implemented your test-case and we have exactly the same result as on our production environment. It works fine on the ios emulator, but the webview renders a white page after account selection on a physical device as it's shown in the video.

https://github.com/user-attachments/assets/ff4d3878-9bfb-4842-bace-4971c3a94437

We are using the following amplify configuration:

`"auth": {
  "plugins": {
    "awsCognitoAuthPlugin": {
      "UserAgent": "aws-amplify/cli",
      "Version": "1.0",
      "IdentityManager": {
        "Default": {}
      },
      "CognitoUserPool": {
        "Default": {
          "PoolId": "myPoolId",
          "AppClientId": "myAppClientId",
          "Region": "myRegion"
        }
      },
      "Auth": {
        "Default": {
          "authenticationFlowType": "USER_PASSWORD_AUTH",
          "OAuth": {
              "WebDomain": "myDomain",
              "AppClientId":  "myAppClientId",                           
              "SignInRedirectURI": "myapp://myapp.link",
              "SignOutRedirectURI": "myapp://myapp.link",
              "Scopes": [
                  "phone",
                  "email",
                  "openid",
                  "profile",
                  "aws.cognito.signin.user.admin"
              ]
          }
        }
      }
    }
  }
}`

The deep link is working fine as we can click on it from different browsers/apps and the app will open fine. We are currently implementing the cognito external provider flow manually using the default browser instead and it's working fine. This is of course painful for us because it mean dropping the whole amplify library as we can't inject a session externally, from our understanding at least.

**Comment by tyllark** [comment]
Hello @pcittadini, thank you for clarifying your exact experience. The main difference between our configuration files is the  Redirect URIs, is yours exactly `myapp://myapp.link`? Or can you provide a more precise example with redacted information. I'm using `myapp://callback/` and `myapp://signout/` on my side.

Since I'm still unable to reproduce the error could you please use your Safari Web inspector to see if any Console or Network errors are being thrown. You will need to enable [web developer features on your mac](https://developer.apple.com/documentation/safari-developer-tools/enabling-developer-features) and [enable inspection on your iOS device](https://developer.apple.com/documentation/safari-developer-tools/inspecting-ios) then you can open the web inspector once you are in the Apple Sign In WebView via `Safari -> Develop -> [YOUR IOS DEVICE].

Unfortunately you cannot inject sessions into the amplify library at this time, though we have been discussing the possibility of allowing this. Technically you can use our [aws_signature_v4](https://pub.dev/packages/aws_signature_v4) package and provide your own credential scope, but that is not ideal if you are using more than a couple of AWS endpoints.

**Comment by tyllark** [comment]
Hi @pcittadini, I was initially using universal links instead of custom url schemes, but I'm still unable to recreate the issue after switching. I'm using my Github Page as my domain to match the format of your redirect uris

![Image](https://github.com/user-attachments/assets/6cc816c7-1fa7-42f1-95a2-574dbe653ca4)

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/2b2b3f26-d857-4ba2-8b31-002e24abe04f" />

Can you please update your redirect uris to be `mycustomschema://` and temporarily remove your custom url scheme to determine if the issue is related to deep links or signInWithWebUI configuration. If this does not help would you be interested in doing a call so we can compare our project configurations?

**Comment by pcittadini** [comment]
hi @tyllark , thanks again for the continous support. A call might be great to have, I am really curious to delve into this and understand if there is something we are doing wrong on our side.

How can we arrange that?

**Comment by sakishu** [comment]
@tyllark 
Hello
 Are you planning to fix this problem?

**Comment by tyllark** [comment]
Hello @sakishu, we are still investigating the problem to identify the root cause. So far I've been unable to reproduce the issue, but have moved some conversations off Github to protect sensitive information. If you have any additional information on how to reproduce the issue I will gladly take a look. 

Could you plese provide me with the following information:

1. How did you provision your Amplify backend? (gen 1, gen 2, cdk, or other means)
2. How did you modify your iOS Xcode project outside the Amplify Flutter [iOS Platform Setup](https://docs.amplify.aws/flutter/start/platform-setup/#ios) guide.
3. What phone models and OS are you reproducing the issue with.

**Comment by tyllark** [comment]
Hello @pcittadini, since we are getting different results using the same dart code I would like for us to focus on cognito, xcode, and phone settings. Could you please provide the following:

1. Provide more details on your Custom Pipeline so I can recreate a similar backend. (I've been testing on Amplify gen 1 and gen 2 provisioned backends).
2. Provide a minimal reproducible Flutter app (ios/xcode files included). I will update the deep link scheme to go to my [Github Page](https://tyllark.github.io/) along with the bundle identifier and signing details.
3. Provide a list of phone models and operating systems that are encountering this issue.

**Comment by sakishu** [comment]
> Hello [@sakishu](https://github.com/sakishu), we are still investigating the problem to identify the root cause. So far I've been unable to reproduce the issue. If you have any additional information on how to reproduce the issue I will gladly take a look.
> 
> Could you please provide me with the following information:
> 
> 1. How did you provision your Amplify backend? (gen 1, gen 2, cdk, or other means)
> 2. How did you modify your iOS Xcode project outside the Amplify Flutter [iOS Platform Setup](https://docs.amplify.aws/flutter/start/platform-setup/#ios) guide.
> 3. What phone models and OS are you reproducing the issue with.

@tyllark 
Sorry, resolved.
It seems the following settings were omitted

"Select Runner, Project -> Runner and then the "Build Settings" tab. Update "iOS Deployment Target" to 13.0 or higher."

**Comment by ekjotmultani** [comment]
Thanks for the update @sakishu, I'm happy that resolved your issue

**Comment by urvashi-k-7span** [comment]
> > Hello [@sakishu](https://github.com/sakishu), we are still investigating the problem to identify the root cause. So far I've been unable to reproduce the issue. If you have any additional information on how to reproduce the issue I will gladly take a look.
> > Could you please provide me with the following information:
> > 
> > 1. How did you provision your Amplify backend? (gen 1, gen 2, cdk, or other means)
> > 2. How did you modify your iOS Xcode project outside the Amplify Flutter [iOS Platform Setup](https://docs.amplify.aws/flutter/start/platform-setup/#ios) guide.
> > 3. What phone models and OS are you reproducing the issue with.
> 
> [@tyllark](https://github.com/tyllark) Sorry, resolved. It seems the following settings were omitted
> 
> "Select Runner, Project -> Runner and then the "Build Settings" tab. Update "iOS Deployment Target" to 13.0 or higher."

I was facing same issue, 
After lots of struggle and time 😢  it is fixed by changing "iOS Deployment Target" to 13.0 or higher."

**Comment by tyllark** [comment]
Hello @urvashi-k-7span, thank you for confirming the solution!

@pcittadini @ProgUser145 @aktumut @KeidiKD, can you please confirm that your iOS project has a Deployment Target of 13.0 or higher? This has been the root cause for some other users.

**Comment by urvashi-k-7span** [comment]
> Hello [@urvashi-k-7span](https://github.com/urvashi-k-7span), thank you for confirming the solution!
> 
> [@pcittadini](https://github.com/pcittadini) [@ProgUser145](https://github.com/ProgUser145) [@aktumut](https://github.com/aktumut) [@KeidiKD](https://github.com/KeidiKD), can you please confirm that your iOS project has a Deployment Target of 13.0 or higher? This has been the root cause for some other users.

Yes, I have "iOS Deployment Target" = 12.0, after changing it to 13.0 it worked.

**Comment by pcittadini** [comment]
@tyllark sorry for the late reply. Unfortunatly as we were depending for an important release on this one, we were busy phasing out amplify from our code base, since we couldn't get a solution and support on this one. Our deployment target has always been > 13.0 and did not affect the outcome.
